"""
Brotochondria — Index Generator
Creates README, link directory, statistics, search guide, and master indexes.
"""
import json
import re
from pathlib import Path

from collectors.links import LinkIndexer
from config import LINK_FOLDER_THRESHOLD
from utils.logger import get_logger

logger = get_logger('index_gen')


class IndexGenerator:
    def __init__(self, db, exports_dir: Path):
        self.db = db
        self.exports_dir = exports_dir
        self.link_indexer = LinkIndexer(db)

    async def export(self):
        logger.info("Generating indexes and guides")
        await self._generate_readme()
        await self._generate_statistics()
        await self._generate_link_directory()
        await self._generate_search_guide()
        await self._generate_channel_guide()
        logger.info("Index generation complete")

    async def _generate_readme(self):
        server = await self.db.fetch_one("SELECT * FROM server LIMIT 1")
        stats = await self.db.get_stats()
        name = server['name'] if server else 'Unknown'

        content = f"""# {name} — Archive

> Generated by **Brotochondria** — Discord Server Extraction Engine

## Quick Stats
- **Messages:** {stats.get('messages', 0):,}
- **Members:** {stats.get('members', 0):,}
- **Attachments:** {stats.get('attachments', 0):,} ({stats.get('attachments_downloaded', 0):,} downloaded)
- **Links:** {stats.get('links', 0):,}
- **Threads:** {stats.get('threads', 0):,}
- **Emojis:** {stats.get('emojis', 0):,}
- **Stickers:** {stats.get('stickers', 0):,}

## Directory Structure
- `channels/` — Message history organized by category/channel/date
- `_metadata/` — Server info, roles, emojis, stickers, settings
- `_members/` — Member directory
- `_audit_log/` — Server audit log
- `_links/` — All links organized by domain
- `_media/` — All downloaded attachments organized by type
- `_indexes/` — This file + guides

## Searching
The `brotochondria.db` file is a SQLite database with FTS5 full-text search.
Open it with [DB Browser for SQLite](https://sqlitebrowser.org/) or any SQLite tool.
See `_indexes/SEARCH_GUIDE.md` for pre-written queries.
"""
        (self.exports_dir / "README.md").write_text(content, encoding='utf-8')

    async def _generate_statistics(self):
        idx_dir = self.exports_dir / "_indexes"
        idx_dir.mkdir(parents=True, exist_ok=True)

        stats = await self.db.get_stats()
        server = await self.db.fetch_one("SELECT * FROM server LIMIT 1")

        stats_data = {
            'server_name': server['name'] if server else 'Unknown',
            'server_id': server['id'] if server else None,
            **stats,
        }
        (idx_dir / "STATISTICS.json").write_text(
            json.dumps(stats_data, indent=2, default=str), encoding='utf-8'
        )

    async def _generate_link_directory(self):
        """Create _links/ directory organized by domain."""
        links_dir = self.exports_dir / "_links"
        links_dir.mkdir(parents=True, exist_ok=True)

        grouped = await self.link_indexer.get_links_by_folder()
        link_stats = await self.link_indexer.get_link_stats()

        # Master index
        all_links = []
        directory_lines = [f"# Link Directory\n\n> {link_stats['total']} total links\n"]

        other_links = []

        for folder, links in sorted(grouped.items(), key=lambda x: -len(x[1])):
            all_links.extend(links)

            if len(links) >= LINK_FOLDER_THRESHOLD:
                # Own folder
                folder_dir = links_dir / _safe(folder)
                folder_dir.mkdir(parents=True, exist_ok=True)

                # JSON
                (folder_dir / "links.json").write_text(
                    json.dumps({
                        'domain': folder,
                        'total_links': len(links),
                        'links': [dict(l) for l in links],
                    }, indent=2, default=str, ensure_ascii=False),
                    encoding='utf-8'
                )

                # Markdown
                md_lines = [f"# Links — {folder}\n\n> {len(links)} links\n\n---\n"]
                for link in links:
                    md_lines.append(f"### {link['url']}")
                    md_lines.append(f"- **Sent by:** {link.get('author_name', '?')}")
                    md_lines.append(f"- **Date:** {link.get('created_at', '?')[:10]}")
                    ctx = (link.get('context', '') or '')[:100]
                    if ctx:
                        md_lines.append(f"- **Context:** \"{ctx}\"")
                    md_lines.append("\n---\n")
                (folder_dir / "links.md").write_text('\n'.join(md_lines), encoding='utf-8')

                directory_lines.append(f"### [{folder}]({_safe(folder)}/links.md) — {len(links)} links")
            else:
                other_links.extend(links)

        # _other/ folder
        if other_links:
            other_dir = links_dir / "_other"
            other_dir.mkdir(parents=True, exist_ok=True)
            (other_dir / "links.json").write_text(
                json.dumps({'domain': '_other', 'total_links': len(other_links),
                            'links': [dict(l) for l in other_links]},
                           indent=2, default=str, ensure_ascii=False),
                encoding='utf-8'
            )
            directory_lines.append(f"### [Other](_other/links.json) — {len(other_links)} links")

        # Master files
        (links_dir / "all_links.json").write_text(
            json.dumps([dict(l) for l in all_links], indent=2, default=str, ensure_ascii=False),
            encoding='utf-8'
        )
        (links_dir / "LINK_DIRECTORY.md").write_text('\n'.join(directory_lines), encoding='utf-8')

    async def _generate_search_guide(self):
        idx_dir = self.exports_dir / "_indexes"
        idx_dir.mkdir(parents=True, exist_ok=True)

        content = """# Brotochondria — Search Guide

Open `brotochondria.db` with [DB Browser for SQLite](https://sqlitebrowser.org/) and run these queries.

## Full-Text Search
```sql
-- Search for a keyword
SELECT author_name, content, created_at, channel_id
FROM messages JOIN messages_fts ON messages.rowid = messages_fts.rowid
WHERE messages_fts MATCH 'your search term'
ORDER BY rank LIMIT 50;
```

## Find Messages by User
```sql
SELECT content, created_at FROM messages
WHERE author_name = 'username' ORDER BY created_at;
```

## Find All Links from a Domain
```sql
SELECT url, author_name, created_at, context FROM links
WHERE domain = 'docs.google.com' ORDER BY created_at;
```

## Find Google Spreadsheets
```sql
SELECT url, author_name, created_at, context FROM links
WHERE category_folder = 'google-spreadsheets' ORDER BY created_at;
```

## Find All Attachments by Type
```sql
SELECT filename, stored_filename, size, drive_path FROM attachments
WHERE content_type LIKE 'image/%' AND downloaded = 1;
```

## Find Documents (PDFs, DOCs)
```sql
SELECT filename, stored_filename, size, drive_path FROM attachments
WHERE (filename LIKE '%.pdf' OR filename LIKE '%.docx' OR filename LIKE '%.doc')
AND downloaded = 1;
```

## Message Count by Channel
```sql
SELECT c.name, COUNT(m.id) as msg_count
FROM messages m JOIN channels c ON m.channel_id = c.id
GROUP BY c.name ORDER BY msg_count DESC;
```

## Most Active Users
```sql
SELECT author_name, COUNT(*) as msg_count
FROM messages GROUP BY author_name
ORDER BY msg_count DESC LIMIT 20;
```

## Messages on a Specific Date
```sql
SELECT author_name, content, created_at FROM messages
WHERE substr(created_at, 1, 10) = '2024-03-15'
ORDER BY created_at;
```

## Forwarded Messages
```sql
SELECT author_name, forwarded_original_author, forwarded_original_content, created_at
FROM messages WHERE is_forwarded = 1;
```
"""
        (idx_dir / "SEARCH_GUIDE.md").write_text(content, encoding='utf-8')

    async def _generate_channel_guide(self):
        idx_dir = self.exports_dir / "_indexes"
        idx_dir.mkdir(parents=True, exist_ok=True)

        channels = await self.db.get_all_channels()
        lines = ["# Channel Guide\n"]

        for ch in channels:
            count = await self.db.get_message_count(ch['id'])
            topic = ch.get('topic', '') or ''
            lines.append(f"### #{ch['name']} ({ch['type']})")
            if topic:
                lines.append(f"> {topic[:200]}")
            lines.append(f"- Messages: {count:,}")
            lines.append("")

        (idx_dir / "CHANNEL_GUIDE.md").write_text('\n'.join(lines), encoding='utf-8')


def _safe(name: str) -> str:
    s = re.sub(r'[\\/:*?"<>|\x00-\x1f]', '_', name or 'unknown')
    return re.sub(r'_+', '_', s).strip('_. ')[:50]
